name: Release Workflow

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v0.1.0, v0.2.0, etc.

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      - name: Build Linux binary
        run: GOOS=linux GOARCH=amd64 go build -o bioinfo-cli-linux-amd64 cmd/app/main.go

      - name: Build macOS binary
        run: GOOS=darwin GOARCH=amd64 go build -o bioinfo-cli-darwin-amd64 cmd/app/main.go

      - name: Build Windows binary
        run: GOOS=windows GOARCH=amd64 go build -o bioinfo-cli-windows-amd64.exe cmd/app/main.go

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            bioinfo-cli-linux-amd64
            bioinfo-cli-darwin-amd64
            bioinfo-cli-windows-amd64.exe

  create-release:
    runs-on: ubuntu-latest
    needs: build-binaries
    if: github.actor == 'joushvak17'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: ./binaries

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
            - Linux: bioinfo-cli-linux-amd64
            - macOS: bioinfo-cli-darwin-amd64
            - Windows: bioinfo-cli-windows-amd64.exe
          files: |
            binaries/bioinfo-cli-linux-amd64
            binaries/bioinfo-cli-darwin-amd64
            binaries/bioinfo-cli-windows-amd64.exe