name: Testing and Linting Workflow

on:
  push:
    branches:
      - master
      - test-ci-pipeline
  pull_request:
    branches:
      - master
      - test-ci-pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      - name: Test with coverage
        run: go test -coverprofile=coverage.out -v ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          files: coverage.out

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Check code formatting
        run: |
          if [[ $(goimports -l .) ]]; then
            echo "Code is not properly formatted. Run 'goimports -w .' to fix."
            exit 1
          fi
        continue-on-error: false

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      
      - name: Run golangci-lint
        run: golangci-lint run