name: Bioinformatics CLI Tool CI/CD Pipeline

on:
  push:
    branches:
      - master
      - test-ci-pipeline
  pull_request:
    branches:
      - master
      - test-ci-pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.0

    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.0

    - name: Test
      run: go test -v ./...

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.0

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      
    - name: Run golangci-lint
      run: golangci-lint run